name: dagger

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
  schedule:
    # 03:07 UTC on Tuesday and Friday
    - cron: '07 03 * * 2,5'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DAGGER_CACHE_FROM: type=gha,scope=dagger-cache
      DAGGER_CACHE_TO: type=gha,mode=max,scope=dagger-cache
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Dagger
        uses: dagger/dagger-for-github@v3
        with:
          cmds: do generator
        env:
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_IMAGE: ${{ secrets.DOCKER_IMAGE }}
